<img src=https://courseware.decoded.com/images/decoded/logo-decoded.png align=left width=100px/>

# Python: Data Processing

---

<small>© COPYRIGHT 2026 DECODED LIMITED. ALL RIGHTS RESERVED. Web: https://decoded.com/ </small>

## Learning Objectives


1. **Data types** Data types in python
2. **Common libraries in data science:** Introduce `pandas` and `numpy` libraries
3. **ETL Mastery:** Ingest "wild" data formats (CSV with bad delimiters, Excel with metadata headers).
4. **Data Hygiene:** Apply a standard operating procedure (SOP) to fix data types and missing values.



---



### Programmes

* Workshop 1.1 - Data Science Accelerator


### Workshop Summary

In this workshop, we transition from basic Python scripting to professional data science practices. We acknowledge that "Happy Path" programming—where data is always clean and properly formatted—is a myth in the real world.

You will learn to function as a data engineer by mastering the ETL (Extract, Transform, Load) pipeline. We start by ingesting "wild" data formats, tackling common pain points like bad delimiters, metadata headers in Excel, and nested JSON structures.

Crucially, we establish a Standard Operating Procedure (SOP) for data hygiene to prevent "silent failures" caused by hidden data type errors (the "Object Trap") and missing values. By the end of this session, you will be able to robustly ingest, clean, and validate messy datasets, ensuring they are ready for downstream analysis.




## Content

### Overview

    
*   Introductions
    *   Purpose: What is the aim of the content?    
    *   Objectives: What will I learn?
    *   Process: How will I learn this content?
    *   Expectations: Am I right for this content?
    *   Applications: Why study this?
*   How do you define complex datasets with collections?
    *   How do I create an use lists of data?
    *   How do I create and use data relationships?
    *   How do I create an used immutable lists of data?
    *   Challenge: Analyse complex data sets
*   How do you analyse complex datasets with loops?
    *   Why repeat code?
    *   What types of loops are there in Python?
    *   Challenge: Modify a `for`-loop to `print()` the elements of a list
    *   Stretch Challenge: Compute aggregate statistics from lists of data
* An introduction to numpy and pandas
    *  Understanding the difference between a list, an array, and a DataFrame
    *  Challenge: Compare `numpy` arrays with python `lists`
* What is a `numpy` array?
    *  Introduce to n-dimensional arrays as efficient grids of values
    *  Challenge: Create a numpy array with `np.array` and get its `.shape`
* What is a `pandas` DataFrame?
    * How to create tabular data structures from dictionaries and lists
    * Challenge: Compare a DataFrame with an array
* How do you extract raw datasets into python?
    * How do you handle "wild" csvs ?
    * How do you address common pain points found in importing Excel spreadsheets?
    * How do you load complex JSON structures?
    * Challenge: Clean dataset    
* How do you keep you data hygienic in Python?
    * How do you perform health check on your data in Python ?
    * How do you enforce the data type in Python?
    * How do you detect and impute missing values?
    * Challenge: Clean dataset    
* Review
    *   What did we learn?
    *   What should I learn next?

### Applications: Why study Data Processing in Python?

Data has become ubiquitous and a diverse range of tasks and problems require data to be performed and solved.

This can vary enormously, from developing a website, creating an analytical report, writing an application for a phone, or creating an AI model. All require data to be sourced, engineered, processed and consumed.

Python is an increasingly popular programming language for processing data efficiently.

---

### How do you define complex datasets with collections?

#### How do I create and use lists of data?

`list`s are ordered and mutable (editable) collections of data, can have duplicates.

They are defined with square brackets e.g.,

```python
prices = ["£1.00", 1.50, None, False, 0, ...]
```

Methods on `list`s include, `.append`,

```python
prices.append(1) # prices is mutable
```

...which illustrates that we can modify them.

To create a list we use square brackets,

In [1]:
locations = ["London", "Leeds", "Manchester"]

As with strings, the first element is at index `0`,

In [3]:
locations[0]

'London'

We can add additional elements to a `list` with `.append`,

In [4]:
locations.append('Cardiff')

Or, to add multiple elements, we can use `.extend`,

In [6]:
locations.extend(["Newport","Bristol","Somewhere"])

In [7]:
locations

['London', 'Leeds', 'Manchester', 'Cardiff', 'Newport', 'Bristol', 'Somewhere']

#### How do I create and use data relationships?

A `dict` is a set of *pairs*.

Where a `list` is a sequence of single elements, in a `dict` each element is a `key:value` pair.

These pairs are effectively a *relationship* between the keys and values.

Defined with curly braces with a comma separating paired (`k:v`) elements, e.g.,

```python
record = {"company": "example", "address": ("London", "UK"), "is_open": False, ...}

record["company"] = "Example LTD." # record is mutable
```

As a technical definition, `dict`s are unordered and mutable collections of data stored in key-value pairs, where the keys must be unique.

In [8]:
#Define a dictionary to hold classroom registration status
city_record = {
    "name": "London",
    "country": "UK",
    "population": 60_000_000
}
 

We access the entires of the dictionary using the *keys*,

In [10]:
#access entries in a dictionary using keys
city_record['population']

60000000

When the keys of a dictionary do little more than "tag" data, they are effectively *records*, as with `city_record`.

But they can be use to *associate* different types of data,

In [11]:
# Associate different types of values with keys in a dictionary
classroom_register = {
    "Sherlock": True,
    "Watson": True,
    "Santa Clause": False
}

Did Sherlock turn up to school today?

In [12]:
classroom_register['Sherlock']

True

We can add keys to existing dictionaries, one at a time,

In [13]:
# add keys/values to existing dictionary
classroom_register['Daniel'] = True
classroom_register

{'Sherlock': True, 'Watson': True, 'Santa Clause': False, 'Daniel': True}

Or several at once,

In [15]:
# Add several students at once
classroom_register.update({
    'Hansle':True, 
    'Gretl':True,
    'Dave':False
})
classroom_register

{'Sherlock': True,
 'Watson': True,
 'Santa Clause': False,
 'Daniel': True,
 'Hansle': True,
 'Gretl': True,
 'Dave': False}

In [16]:
# Check if a student is registered in the dictionary
classroom_register['Daniel']

True

A recent addition to python, the `|` operator on dictionaries allows you to create a new dictionary rather than *update* an existing one,

In [30]:
# Create a new dictionary with an additional student using | operator

# Create a new dictionary with an additional student using | operator

#if the same value exists in both dictionaries then the value from dictionary 2 will overwrite the value from dictionary 1
 
dct1 = {'a':1,'b':2,'c':3}

dct2 = {'x':10,'y':25,'z':26}

new_dct = dct1 | dct2

print(new_dct)
 

{'a': 1, 'b': 2, 'c': 3, 'x': 10, 'y': 25, 'z': 26}


In [33]:
# How do we check if a student is registered?
new_dct.get('g', 1)

1

False

### How do I create an used immutable lists of data?

`tuple`s are ordered and immutable collections of data, which can have duplicates.

Often defined with parentheses, e.g.
```python
address = ("London", "UK", ...)
```

but, only *a comma* is actually required,

```python
city = "London", "UK"
```

`tuple`'s main feature is their immutability (they cannot be modified),
```python
# ERROR: address[0] = "Leeds" # NOT ALLOWED, immutable
```

`tuple`s are simple ways of representing rows of data, which we almost never wish to change.

Consider the `list` below called `table` which contains `tuple`s.

We can `.append` an additional `tuple` to the `list` (because *it* is mutable), but we cannot modify it's elements,

In [17]:
# Define a table as a list of lists

table = [
    [1, "Alice", "UK"],
    [2, "Eve", "FR"],
]
 
table.append( [3, "Bob", "US"] )
 

In [18]:
table

[[1, 'Alice', 'UK'], [2, 'Eve', 'FR'], [3, 'Bob', 'US']]

To access `Alice` we first index to obtain the first entry in `table`, which is index `[0]` and then the second entry in that `tuple`, ie., index `[1]`,

In [20]:
# Access a certain entry in the table

table[0][1]

'Alice'

In [ ]:
# We can modify a certain entry in the table



---

### How do you analyse complex datasets with loops?

#### Why repeat code?
Simple, or scalar, data is the kind which is only a single value.

Complex, aggregate, or composite data has several parts or elements.

A collection is a group of several separate pieces of data which often need to be processed the same way.

Consider the `prices` collection below. We display each element converted to a USD price (supposing a `1.3x` conversion ratio).

Each element of `prices` is processed the same way, so that two lines of code are repeated,

In [21]:
# Why is this code repetitive? How can we improve it?

prices = [2, 4, 5]
 
price = prices[0]
usd_price = 1.3 * price
print(usd_price)
 
price = prices[1]
usd_price = 1.3 * price
print(usd_price)
 
price = prices[2]
usd_price = 1.3 * price
print(usd_price)
 

2.6
5.2
6.5


We can simplify this with a for-loop, which repeats the (indented) *body* for each element in an existing dataset,

In [25]:
# We can simply repetitve codes and replace it with a loop
for price in prices:
    print(f"Price in USD: ${1.3 * price}")

Price in USD: $2.6
Price in USD: $5.2
Price in USD: $6.5


Loops also handle the case where we don't know how many elements a collection has, or how often we need to repeat some code.

#### What types of loops are there in Python?

There are two types of loops in Python used to repeat commands, `for`-loops and `while`-loops.

For loops will continue to run until they reach the end of the sequence, whereas while loops will stop running when some condition is met.

Syntax for `for` loops:

```python
for <element label> in <sequence>:
    <some action>
```


Syntax for `while` loops:

```python
while <some condition>:
    <some action>
```

#### Modify a `for`-loop to `print()` the elements of a list

Consider the code example below,


```python
names = ["Sherlock", "Watson", "Irene"]
total = 0

for n in names:
    ...
```

* By replacing `...`, `print()` each name in the list
    * HINT: `n` is the name we've given to each element
* `n` is just a label (, variable), change `n` to `name`
    * HINT: change it in the `for` line and the `print()`
* Update `total` to the total length of all the characters in all the `names`
    * HINT: `+= len(...)`
* Define a list, called `cities`, and `print()` each using a `for`-loop
    * The cities should be `"Paris", "London", "New York"`
    * HINT: you can use any label for the element, call it `city`
* `.append()` each `city` to your `names` list
    * HINT: `names.append(...)`

In [26]:
names = ["Sherlock", "Watson", "Irene"]
total = 0

for n in names:
    print(n)

Sherlock
Watson
Irene


In [34]:
cities = ["Paris", "London", "New York"]

names = ["Sherlock", "Watson", "Irene"]
 
for city in cities:

    print(city)

    names.append(city)

print(names)    

 

Paris
London
New York
['Sherlock', 'Watson', 'Irene', 'Paris', 'London', 'New York']


### An introduction to `numpy` and `pandas`

`numpy` and `pandas` are powerful Python libraries which work with two different types of data structures, namely:

- `Numpy` Arrays
- `Pandas` DataFrames

### What is a `numpy` array?

A `numpy` array is a grid of values.

A 1-dimensional array is like a vector of numbers,

```python
array([ 1, -1, -10])
```

A 2-dimensional array is like a simple matrix, similar to a table with columns and rows,

```python
array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])
```

`numpy` arrays can reach as many dimensions as you want.

An n-dimensional array is like a series of matrices stacked on top of one another,

```python
array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])
```


### How do I create numpy arrays?

In order to work with numpy arrays, you first need to import `numpy` as follows,

```python
import numpy as np
```

Importing numpy as `np` is a convention.

Then you can use the `np.array()` function to create arrays by providing some data values,  

```python
np.array([1, 2, 3, 4])
```

These data values can be in the form of lists (as shown in the example), tuples, dataframes, and other data forms.

#### Compare `numpy` arrays with python `lists`

- Run the following code to create a list and a numpy array with the same values:

```python
import numpy as np
ex_list_1 = [10, 20, 30, 40]
ex_list_2 = [40, 30, 20, 10]
ex_array_1 = np.array(ex_list_1)
ex_array_1 = np.array(ex_list_2)
```

- Print both objects. What are the difference in their creation and the way they look after printing?
- Use the `type()` function on each of them. What does it return?

In [36]:
# 
import numpy as np
# Create two lists
ex_list_1 = [10, 20, 30, 40]
ex_list_2 = [40, 30, 20, 10]
ex_array_1 = np.array(ex_list_1)
ex_array_2 = np.array(ex_list_2)



* Why does it matter to convert list to `numpy` array?

In [38]:

# This throws a TypeError. Lists cannot divide lists.
# Can I multiply two lists?


# This one works
cal_two_lists = ex_list_1 + ex_list_2

# What do you expect the output to be?

# Can I multiply two numpy arrays?
cal_two_arrays = ex_array_1 + ex_array_2
print(cal_two_lists)
print(cal_two_arrays)

[10, 20, 30, 40, 40, 30, 20, 10]
[50 50 50 50]


### Group Challenge: operating lists and `numpy` arrays

Suppose you have two sets of data
```python
height = [1, 2, 3]
growth = [1, 1, 1]
```

Predict the output of the following operations for both a Python List and a Numpy Array. Then run the code to verify

|   Operation | Python list outcome   |  Numpy array outcome
|:-------|:--------------|:----------------
| `height`+`growth` | ? | ?
| `height`/`growth` | ? | ?
| `height`/2 | ? | ?
| `height`** 2 | ? | ?

In [41]:
# Write your observations below:
height = [1, 2, 3]
growth = [1, 1, 1]
height_arr = np.array([1, 2, 3])
growth_arr = np.array([1, 1, 1])



array([1., 2., 3.])

#### Create a numpy array with `np.array` and get its `.shape`

- Run the following code to create an array:
    ```python
    import numpy as np
    
    arr_1 = np.array([1, 2, 3])
    arr_2 = np.array([[1, 2, 3],
                    [1, 1, 1],
                    [4, 5, 6]])
    
    arr_3 = np.array([[[1, 2, 3],
                    [1, 1, 1],
                    [4, 5, 6]],
                      
                    [[0, 0, 0],
                    [0, 0, 0],
                    [0, 0, 0]]]
                    )
    ```
- Use `arr_1.shape`, `arr_2.shape`, etc. to get the shape of the arrays. What do you get?


In [45]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([[1, 2, 3],
                [1, 1, 1],
                [4, 5, 6]])

arr_3 = np.array([[[1, 2, 3],
                [1, 1, 1],
                [4, 5, 6]],
                  
                [[0, 0, 0],
                [0, 0, 0],
                [0, 0, 0]]]
                )
arr_3.shape

(2, 3, 3)

#### Quiz: The broken array
* The broken array
    - The Client sent this data, but the architect says it's impossible to build. Why?
    ```python
    [1,2,3]
    [4,5]
    [7,8,9]
    ```

* Run the following code:
    ```python
        broken_array = np.array([
        [1, 2, 3],
        [4, 5],
        [7, 8, 9]
    ])
    ```
* Why will this crash with a "ValueError"?
* How do you fix it?


In [52]:
# Write your solution here
broken_array = np.array([
    [1, 2, 3],
    [4, 5, None],
    [7, 8, 9]
])

broken_array

array([[1, 2, 3],
       [4, 5, None],
       [7, 8, 9]], dtype=object)

### What is a `pandas` DataFrame?

If you imagine a spreadsheet you are imagining something very close to a `pandas` DataFrame.

A `pandas` DataFrame is a two-dimensional grid of values, a table with named columns and rows.

### How do I create a Pandas DataFrame?

In order to work with a Pandas DataFrame, you first need to import `pandas` as follows,

```python
import pandas as pd
```

Importing pandas as `pd` is a convention.

Then you can use the `pd.DataFrame()` function to create DataFrames by providing some data values and column names, below are a couple of examples of how this can be done.  

- Using a dictionary,

```python
pd.DataFrame({'name': ['Alice', 'Bob'],'age': [25, 30]})
```

- Using a list of lists and specifying column names,

```python
pd.DataFrame([['Alice', 25],['Bob', 30]], columns=['name', 'age'])
```

In [54]:
import pandas as pd

In [62]:
# Create your first dataframe here
my_df = pd.DataFrame({'name': ['Alice', 'Bob'],'age': [25, 30]})
my_df

,name,age
0,Alice,25
1,Bob,30


#### Compare a DataFrame with an array

- Run the following code. It will create two identical 2-dimensional grids of values. In one case it is a pandas DataFrame. In another one it's a numpy array.

```python
import numpy as np
import pandas as pd
ex_array = np.array([[1, 2, 3],
                  [1, 1, 1],
                  [4, 5, 6]])

ex_df = pd.DataFrame([[1, 2, 3],
                     [1, 1, 1],
                     [4, 5, 6]])

ex_df.columns = ['col_1', 'col_2', 'col_3']

```

- Use the `display()` function on both objects. What's the difference between them?

'/home/lab18/Documents/my-work/week2'

---

## Data Processing - implement the ETL process with `pandas`

"Data rarely comes to us clean. In the real world, a Data Scientist spends 60-80% of their time on **ETL** (Extract, Transform, Load). Today we are going to solve the specific pain points that cause Python scripts to crash."



### Import Libraries

In [61]:
# Import necessary libraries

import pandas as pd
import numpy as np
import math
import time

# Optional: Adjust display settings to see more columns/rows


# How do you ensure the libraries are imported correctly?


---

### Extract: Ingesting "Wild" Data Types

You may already know `pd.read_csv('file.csv')`. I am going to show you what happens when files are messy.

**What is done**: We are moving away from the simple pd.read_csv('clean_file.csv') command. Instead, we are using advanced parameters like `sep='|'` , `encoding='latin-1'`, and `skiprows=2` to force Python to read files that are formatted incorrectly for standard tools.

**Why it matters**: In the real world, data never arrives clean. It comes from legacy systems (which use weird separators), international teams (different encodings), or Excel reports meant for humans (with "titles" in the first few rows). If you don't know these parameters, your script crashes immediately, and you cannot start your job.

### 1 The CSV (Comma Separated Values)
**The problem:** The file `raw_sales.csv` uses pipes `|` instead of commas and has `latin-1` encoding (common in Excel exports on Windows).

In [63]:
# COMMON ERROR: This will fail
df = pd.read_csv('raw_sales.csv')
df.head()



,ID|Revenue|Date|Target
101|$12,000.00|2023-01-01|100
102|$500.50|01/02/2023|,NaN
103|200|2023-March-05|150,NaN
104|$1,200.00|2023-01-01|
105|$15,500.25|2023-04-10|200


**Solution** Specifiy separator and encoding

In [64]:
df = pd.read_csv('raw_sales.csv', delimiter='|')
df.head()

,ID,Revenue,Date,Target
0,101,"$12,000.00",2023-01-01,100.0
1,102,$500.50,01/02/2023,NaN
2,103,200,2023-March-05,150.0
3,104,"$1,200.00",2023-01-01,NaN
4,105,"$15,500.25",2023-04-10,200.0


### 2 The Excel File (.xlsx)
**The problem:**
Excel reports often have titles, dates, or logos in the first few rows. Pandas assumes the first row (Row 0) is the header.

**Example**
`targets.xlsx` has a "Report Title" in the first 2 rows. The actual header is on Row 3.

**Solution**
We use `skiprows` in `read_excel()` to adjust

In [68]:
# Use read_excel to load the Excel file
# Specify the sheet name if necessary
# ex_df = pd.read_excel('targets.xlsx')
# ex_df.head()

# How do yu ensure the Excel file is loaded correctly?


# Display the first few rows of the dataframe


In [ ]:
# We can specify skiprows to skip initial rows that are not part of the data

# What if the data file contains an error?


Excel Loaded Successfully:


,Region,Q1_Target,Manager
0,North,50000,Alice
1,South,60000,Bob
2,East,45000,Charlie
3,West,70000,Dana


### 3 JSON

You may already know `pd.read_json('file.json')`. I am going to show you what happens when files are messy.

**The problem:** JSON often contains nested dictionaries.

In [70]:

# Read JSON file using read_json
df_json = pd.read_json('user_logs.json')

# Check if JSON file is loaded correctly
df_json.head()

# Display the first few rows of the dataframe


# What if the JSON file contains an error?


,user_id,name,details
0,1,Alice,"{'login_count': 5, 'plan': 'premium'}"
1,2,Bob,"{'login_count': 1, 'plan': 'free'}"
2,3,Charlie,"{'login_count': 10, 'plan': 'premium'}"


* Notice 'details' is a single column with {dicts} inside. How could we fix it ?

##### We can flatten the dataframe using `pd.json_normalize()`

In [76]:
import pandas as pd
import json

# Load the raw data to see the problem
# Notice 'details' is a single column with {dicts} inside
with open('user_logs.json', 'r') as f:
    raw_json = json.load(f)

df_json = pd.json_normalize(raw_json)
df_json.head()
# we can fix: json_normalize
# This function "flattens" the nested keys into new columns using dot notation


# Display the first few rows of the normalized dataframe

# What if the JSON file contains an error?

,user_id,name,details.login_count,details.plan
0,1,Alice,5,premium
1,2,Bob,1,free
2,3,Charlie,10,premium


---

### The SOP: Standard Operating Procedure for Cleaning

**Note:** Stop here. Stress that **loading != ready**.
Do NOT jump to analysis yet. We must pass the **SOP Checklist**:
1.  **Health Check:** `.info()`
2.  **Clean Headers:** Standardize names.
3.  **Type Enforcement:** Fix "Objects".
4.  **Null Handling:** Detect and Fill.

---


##### What is done:
We are implementing a rigid "Standard Operating Procedure" (SOP). This involves checking `.info()` immediately, stripping currency symbols `($, ,)` from numbers, forcing columns into float or datetime formats, and making a conscious decision about how to fill missing values `(NaN)`.

---

##### Why it matters:

This prevents "Silent Failures." A column containing "$1,000" looks like a number to a human, but Python sees it as a text string (Object). If you try to calculate the average revenue on this column, Python might just concatenate the strings or crash later in a machine learning model. Cleaning before analysis is the only way to trust your results.

---

#### Step 1: The Health Check

In [ ]:
# Check types. 
df.info()

# We need to convert it to numeric for analysis.

# Convert 'Revenue' to numeric, removing '$' and ','

--- Data Info ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   ID       6 non-null      int64  
 1   Revenue  6 non-null      object 
 2   Date     6 non-null      object 
 3   Target   3 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes


* Check types. Notice 'Revenue' is an object (string) because of the '$' sign.


####  Step 2: Cleaning Headers
Spaces in column names are annoying. Let's make them `snake_case`.

In [85]:
# Spaces in column names can be problematic. We can rename them.
# Check the column names
df.columns = df.columns.str.strip()
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df.columns

Index(['id', 'revenue', 'date', 'target'], dtype='str')

#### Step 3: Type Enforcement (String to Float)
**Task:** Convert `$12,000.00` (String) -> `12000.0` (Float).

In [86]:
# 1. Access the string accessor (.str)
df['revenue'] = df['revenue'].astype(str)


# 2. Replace symbols ($ and ,)
df['revenue'] = df['revenue'].str.replace('$', '')
df['revenue'] = df['revenue'].str.replace(',', '')

# 3. Cast to float (.astype)
df['revenue'] = df['revenue'].astype(float)
df
# 4. Chain the operations together

,id,revenue,date,target
0,101,12000.00,2023-01-01,100.0
1,102,500.50,01/02/2023,NaN
2,103,200.00,2023-March-05,150.0
3,104,1200.00,2023-01-01,NaN
4,105,15500.25,2023-04-10,200.0
5,106,800.00,12/05/2023,NaN


#### Step 4: DateTime Conversion
**The problem:** There are mixed date formats (`2023-01-01` vs `01/02/2023`) in the dataframe

**Solution:** Use `pd.to_datetime()` to fix it

In [88]:

# Change the date column to datetime format
df['date'] = pd.to_datetime(df['date'], format = 'mixed', errors='coerce')
df.info()
# Use format settings to handle mixed date formats


# Turn unparseable data into NaT (Not a Time) instead of crashing

# Check the converted dates


<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype         
---  ------   --------------  -----         
 0   id       6 non-null      int64         
 1   revenue  6 non-null      float64       
 2   date     6 non-null      datetime64[us]
 3   target   3 non-null      float64       
dtypes: datetime64[us](1), float64(2), int64(1)
memory usage: 324.0 bytes


In [96]:
df['date']

0   2023-01-01
1   2023-01-02
2   2023-03-05
3   2023-01-01
4   2023-04-10
5   2023-12-05
Name: date, dtype: datetime64[us]

#### Step 5: Handling Missing Data (Imputation)
**The problem:** the column `Target` has missing values.

**Solution**

1. We can impute the missing values with different measures `.fillna()`
2. We can delete rows where ANY column is missing `.dropna()`
3. We can delete rows only if a specific column is missing `.dropna(subset=[''])`
4. We can replace with constant fill


In [97]:
df

,id,revenue,date,target
0,101,12000.00,2023-01-01,100.0
1,102,500.50,2023-01-02,NaN
2,103,200.00,2023-03-05,150.0
3,104,1200.00,2023-01-01,NaN
4,105,15500.25,2023-04-10,200.0
5,106,800.00,2023-12-05,NaN


In [98]:

# Handling Missing Values

# Count the number of missing values in each column

# Option A: Delete rows where ANY column is missing

# Option B: Delete rows only if a SPECIFIC column is missing
# (e.g., delete rows with no 'target', but keep rows)

# Calculate mean (ignoring NaNs automatically)


# Fill NaNs
df.isna().sum()

# Check missing values after handling


id         0
revenue    0
date       0
target     3
dtype: int64

### Key Takeaways

**1. Real-World Data is "Wild"**
Standard functions like `pd.read_csv()` often fail on real business data. You now know how to handle:
* **Encoding Errors:** Switching to `latin-1` when standard UTF-8 fails.
* **Bad Delimiters:** Handling pipes `|` or tabs instead of commas.
* **Metadata Rows:** Using `skiprows` to bypass report headers in Excel.

**2. The Cleaning SOP is Non-Negotiable**
We introduced the **Standard Operating Procedure (SOP)** to prevent "Silent Failures":
* **Health Check:** Always run `.info()` first to spot the "Object Trap" (numbers hidden as strings).
* **Type Enforcement:** You must explicitly cast columns to `float` or `datetime`. Python will not guess for you.
* **Null Strategy:** Never blindly drop data. Decide whether to Drop, Fill with Mean, or Flag missing values.

